### ISSUE TITLE
add class_sampler to the experiment module 

### ISSUE THREAD

**Issue by junlinguo** [junlinguo/CellViT-Kidney#1]
https://github.com/junlinguo/CellViT-Kidney/blob/main/cell_segmentation/experiments/experiment_cellvit_instance.py#L892-L915

**Comment by windygoo** [comment]
> https://github.com/junlinguo/CellViT-Kidney/blob/main/cell_segmentation/experiments/experiment_cellvit_instance.py#L892-L915

我也是做这个方向的？加个微信交流一下？

**Comment by junlinguo** [comment]
好的！ 感谢您的关注呀！ 我们的code 进行了更新，之后会放在新的GitHub repository里

https://arxiv.org/abs/2411.00078 这个是这个work最新的更新. 欢迎互相合作或者引用我们的工作

微信：2570564925

________________________________
